import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readdir, readFile, stat } from "node:fs/promises";
import { createRequire } from "node:module";
import { test } from "node:test";
import path from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import { sources, variants } from "../scripts/asset-manifest.mjs";

const require = createRequire(import.meta.url);
const sharp = require("sharp");
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputDir = path.join(root, "assets", "optimized");
const expectedFilenames = Object.keys(sources)
  .flatMap((key) => variants.map(({ width }) => `${key}-${width}.webp`))
  .concat("asset-meta.js")
  .sort();

test("ELORA key visual belongs to the deterministic asset contract", () => {
  assert.ok(sources["elora-keyvisual"]);
  assert.equal(path.basename(sources["elora-keyvisual"]), "elora-keyvisual.jpg");
});

test("NIKE visual study uses the approved main screenshot source", () => {
  assert.ok(sources["nike-study"]);
  assert.equal(path.basename(sources["nike-study"]), "nike-visual-study-main.png");
});

test("AI Campaign Archive home preview uses the approved screenshot source", () => {
  assert.ok(sources["ai-archive-main"]);
  assert.equal(path.basename(sources["ai-archive-main"]), "ai-campaign-archive-main.png");
});

test("optimized directory contains exactly the manifest output set", async () => {
  assert.deepEqual((await readdir(outputDir)).sort(), expectedFilenames);
});

test("every runtime image is a valid, bounded WebP variant", async () => {
  for (const key of Object.keys(sources)) {
    const decodedWidths = new Map();

    for (const { width } of variants) {
      const filename = path.join(outputDir, `${key}-${width}.webp`);
      const info = await stat(filename);
      const metadata = await sharp(filename).metadata();

      assert.equal(metadata.format, "webp", `${filename} is not WebP`);
      assert.ok(metadata.width > 0, `${filename} has no decoded width`);
      assert.ok(metadata.width <= width, `${filename} exceeds its ${width}px maximum`);
      assert.ok(info.size > 0, `${filename} is empty`);
      assert.ok(info.size < 900_000, `${filename} exceeds 900 KB`);
      decodedWidths.set(width, metadata.width);
    }

    assert.ok(
      decodedWidths.get(1280) >= decodedWidths.get(480),
      `${key}-1280.webp is narrower than ${key}-480.webp`,
    );
  }
});

test("generated asset metadata reserves the decoded 1280-variant dimensions", async () => {
  const source = await readFile(path.join(outputDir, "asset-meta.js"), "utf8");
  const context = vm.createContext({ window: {} });
  vm.runInContext(source, context, { filename: "asset-meta.js" });
  const metadata = context.window.PORTFOLIO_IMAGE_META;

  assert.deepEqual(Object.keys(metadata), Object.keys(sources));
  for (const key of Object.keys(sources)) {
    const decoded = await sharp(path.join(outputDir, `${key}-1280.webp`)).metadata();
    assert.deepEqual(
      { ...metadata[key] },
      { width: decoded.width, height: decoded.height },
      `${key} metadata does not match its runtime image`,
    );
  }
});

test("generated bytes use the manifest encoder settings", async () => {
  for (const [key, source] of Object.entries(sources)) {
    for (const { width, quality } of variants) {
      const filename = path.join(outputDir, `${key}-${width}.webp`);
      const actual = await readFile(filename);
      const expected = await sharp(source)
        .rotate()
        .resize({ width, withoutEnlargement: true })
        .webp({ quality, effort: 5 })
        .toBuffer();
      const digest = (buffer) => createHash("sha256").update(buffer).digest("hex");

      assert.equal(
        digest(actual),
        digest(expected),
        `${filename} was not encoded at manifest quality ${quality}`,
      );
    }
  }
});
