import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readdir, readFile, stat } from "node:fs/promises";
import { createRequire } from "node:module";
import { test } from "node:test";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { sources, variants } from "../scripts/asset-manifest.mjs";

const require = createRequire(import.meta.url);
const sharp = require("sharp");
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputDir = path.join(root, "assets", "optimized");
const expectedFilenames = Object.keys(sources)
  .flatMap((key) => variants.map(({ width }) => `${key}-${width}.webp`))
  .sort();

test("optimized directory contains exactly the manifest output set", async () => {
  assert.deepEqual((await readdir(outputDir)).sort(), expectedFilenames);
});

test("every runtime image is a valid, bounded WebP variant", async () => {
  for (const key of Object.keys(sources)) {
    const decodedWidths = new Map();

    for (const { width } of variants) {
      const filename = path.join(outputDir, `${key}-${width}.webp`);
      const info = await stat(filename);
      const metadata = await sharp(filename).metadata();

      assert.equal(metadata.format, "webp", `${filename} is not WebP`);
      assert.ok(metadata.width > 0, `${filename} has no decoded width`);
      assert.ok(metadata.width <= width, `${filename} exceeds its ${width}px maximum`);
      assert.ok(info.size > 0, `${filename} is empty`);
      assert.ok(info.size < 900_000, `${filename} exceeds 900 KB`);
      decodedWidths.set(width, metadata.width);
    }

    assert.ok(
      decodedWidths.get(1280) >= decodedWidths.get(480),
      `${key}-1280.webp is narrower than ${key}-480.webp`,
    );
  }
});

test("generated bytes use the manifest encoder settings", async () => {
  for (const [key, source] of Object.entries(sources)) {
    for (const { width, quality } of variants) {
      const filename = path.join(outputDir, `${key}-${width}.webp`);
      const actual = await readFile(filename);
      const expected = await sharp(source)
        .rotate()
        .resize({ width, withoutEnlargement: true })
        .webp({ quality, effort: 5 })
        .toBuffer();
      const digest = (buffer) => createHash("sha256").update(buffer).digest("hex");

      assert.equal(
        digest(actual),
        digest(expected),
        `${filename} was not encoded at manifest quality ${quality}`,
      );
    }
  }
});
